"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var resource_config_1 = require("./resource.config");
exports.formResourceConfig = resource_config_1.formResourceConfig;
var resources_service_1 = require("./resources.service");
exports.formResources = resources_service_1.formResources;
var resource_service_1 = require("./resource.service");
exports.formResourceService = resource_service_1.formResourceService;
var resource_component_1 = require("./resource.component");
exports.formResourceComponent = resource_component_1.formResourceComponent;
var view_component_1 = require("./view/view.component");
exports.formResourceViewComponent = view_component_1.formResourceViewComponent;
var edit_component_1 = require("./edit/edit.component");
exports.formResourceEditComponent = edit_component_1.formResourceEditComponent;
var delete_component_1 = require("./delete/delete.component");
exports.formResourceDeleteComponent = delete_component_1.formResourceDeleteComponent;
var create_component_1 = require("./create/create.component");
exports.formResourceCreateComponent = create_component_1.formResourceCreateComponent;
var index_component_1 = require("./index/index.component");
exports.formResourceIndexComponent = index_component_1.formResourceIndexComponent;
var resource_routes_1 = require("./resource.routes");
exports.formResourceRoutes = resource_routes_1.formResourceRoutes;
var resource_module_1 = require("./resource.module");
exports.formResource = resource_module_1.formResource;
